{{- range .Values.synced }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-{{ .name }}
spec:
  hostAPI: {{ $.Values.infisical.hostAPI }}
  syncConfig:
    resyncInterval: {{ $.Values.infisical.resyncInterval | quote }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ $.Values.infisical.projectSlug }}
        envSlug: {{ $.Values.infisical.envSlug }}
        secretsPath: {{ .path | quote }}
      credentialsRef:
        secretName: {{ $.Values.infisical.credentials.secretName }}
        secretNamespace: {{ $.Values.infisical.credentials.secretNamespace }}
  managedKubeSecretReferences:
    - secretName: {{ .secretName }}
      secretNamespace: {{ .namespace }}
      creationPolicy: Orphan
{{- end }}
