{{- $ingresses := list
  (dict "name" "app" "host" .Values.app.hostname "service" "app" "port" .Values.app.port)
  (dict "name" "api" "host" .Values.api.hostname "service" "api" "port" .Values.api.port)
  (dict "name" "convex" "host" .Values.convex.hostnames.cloud "service" "convex-backend" "port" 3210)
}}
{{- range $ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: {{ .service }}
      port:
        number: {{ .port }}
  tls:
    - hosts:
        - {{ .host }}
{{- end }}
