{{- if .Values.preview.enabled }}
{{- $infisical := .Values.preview.infisical }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    lisptc.io/preview: "true"
{{- range .Values.preview.synced }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: {{ $infisical.hostAPI }}
  syncConfig:
    resyncInterval: {{ $infisical.resyncInterval | quote }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ $infisical.projectSlug }}
        envSlug: {{ $infisical.envSlug }}
        secretsPath: {{ .path | quote }}
      credentialsRef:
        secretName: {{ $infisical.credentials.secretName }}
        secretNamespace: {{ $infisical.credentials.secretNamespace }}
  managedKubeSecretReferences:
    - secretName: {{ .secretName }}
      secretNamespace: {{ $.Release.Namespace }}
      creationPolicy: Owner
      {{- with .secretType }}
      secretType: {{ . }}
      {{- end }}
      {{- with .template }}
      template:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
