resources:
  requests: { cpu: 10m, memory: 64Mi }
  limits: { cpu: 200m, memory: 256Mi }
config:
  registries:
    - name: GitHub Container Registry
      api_url: https://ghcr.io
      prefix: ghcr.io
      ping: no
      credentials: pullsecret:argocd/ghcr-pull
