apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lisptc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/1hachem/lisptc
    targetRevision: main
    path: charts/lisptc
  destination:
    server: https://kubernetes.default.svc
    namespace: lisptc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
