infisical:
  hostAPI: https://app.infisical.com/api
  projectSlug: listptc-nz-qj
  envSlug: prod
  resyncInterval: "1m"
  credentials:
    secretName: lisptc-infisical-cred
    secretNamespace: infisical

synced:
  - name: tailscale
    path: /tailscale
    secretName: operator-oauth
    namespace: tailscale
  - name: db
    path: /db
    secretName: lisptc-db
    namespace: lisptc
  - name: convex
    path: /convex
    secretName: lisptc-convex
    namespace: lisptc
  - name: api
    path: /api
    secretName: lisptc-api
    namespace: lisptc
  - name: ai
    path: /ai
    secretName: lisptc-ai
    namespace: lisptc
  - name: analytics
    path: /analytics
    secretName: lisptc-analytics
    namespace: lisptc
  - name: web
    path: /web
    secretName: lisptc-web
    namespace: lisptc
