infisical:
  hostAPI: https://app.infisical.com/api
  projectSlug: listptc-nz-qj
  envSlug: prod
  resyncInterval: "1m"
  credentials:
    secretName: lisptc-infisical-cred
    secretNamespace: infisical

synced:
  - name: tailscale
    path: /tailscale
    secretName: operator-oauth
    namespace: tailscale
  - name: db
    path: /db
    secretName: lisptc-db
    namespace: lisptc
  - name: convex-deploy
    path: /convex-deploy
    secretName: lisptc-convex-deploy
    namespace: lisptc
  - name: convex
    path: /convex
    secretName: lisptc-convex
    namespace: lisptc
  - name: api
    path: /api
    secretName: lisptc-api
    namespace: lisptc
  - name: ai
    path: /ai
    secretName: lisptc-ai
    namespace: lisptc
  - name: analytics
    path: /analytics
    secretName: lisptc-analytics
    namespace: lisptc
  - name: web
    path: /web
    secretName: lisptc-web
    namespace: lisptc
  - name: ghcr-lisptc
    path: /ghcr
    secretName: ghcr-pull
    namespace: lisptc
    secretType: kubernetes.io/dockerconfigjson
    template: &ghcr
      includeAllSecrets: false
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"{{ .GHCR_USERNAME.Value }}","password":"{{ .GHCR_TOKEN.Value }}","auth":"{{ printf "%s:%s" .GHCR_USERNAME.Value .GHCR_TOKEN.Value | encodeBase64 }}"}}}'
  - name: github
    path: /github
    secretName: github-token
    namespace: argocd
  - name: ghcr-argocd
    path: /ghcr
    secretName: ghcr-pull
    namespace: argocd
    secretType: kubernetes.io/dockerconfigjson
    template: *ghcr
